import java.util.ArrayList;
import java.util.Arrays;

public class Sub_array_with_given_sum {
    public static void main(String[] args) {
        int[] inputArr = { 15, 2, 4, 8, 9, 5, 10, 23 }; // Take the input array...
        int target = 23;// The target value...

        ArrayList<Integer> result = findSubArray(inputArr, target); // Call the function...

        System.out.println(result); // Print the final subarray result...
    }

    // Function...
    private static ArrayList<Integer> findSubArray(int[] arr, int target) {
        ArrayList<Integer> result = new ArrayList<>(); // Take a ArrayList for storing and returning result...
        for (int i = 0; i < arr.length; i++) { // Traversal every elements in the array...
            int curr = 0; // Take the current sum 0 after everay traversal...
            for(int j = i; j < arr.length; j++) { // Traversal every element after ith element of the array...
                curr += arr[j]; // Increase the current sum value...
                if(curr == target) { // If the current sum and the target is match then retun the final result...
                    result.add(i + 1);
                    result.add(j + 1);
                    return result;
                }
            }
        }
        result.add(-1);
        return result;
    }
}